/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.7 */
/* Wed Aug 20 10:20:38 2025 */

/* parameterized module instance */
PLL __ (.CLKI( ), .RST( ), .CLKOP( ), .LOCK( ));
